env/includes/settings/apps/tk-multi-workfiles2.yml
env/includes/settings/tk-maya.yml
hooks/tk-multi-workfiles2/scene_operation_tk-maya.py

Modified hook scene_operation_tk-maya of tk-multi-workfiles2 app to set default render path, resolution, image format on file open.

#439: Set Maya defaults on file open

---

core/templates.yml

All the departments are going to follow this, hence merging it with templates.yml.

Update the delimiter for output key, to use “-“ instead of “_”

---

core/hooks/name_converter.py
core/templates.yml
core/templates/ingest.yml

This will allow you to convert sg_client_name field to code field, for any entity type, and vice versa.

name_converter functionality added to SGTK templates

---

env/includes/settings/apps/tk-multi-workfiles2.yml
env/includes/settings/tk-nuke.yml
hooks/tk-multi-workfiles2/scene_operation_tk-nuke.py

For TRAINING show mainly. Per shot resolution support.

#483: set seq shot setting values in nuke

---

hooks/tk-multi-workfiles2/scene_operation_tk-maya.py
hooks/tk-multi-workfiles2/scene_operation_tk-nuke.py

Rename nuke format as SHOW_FORMAT (as set in knob defaults).
Get role from SG step instead of os env.

Remove test print. Rename format.  Get role from SG.

---

env/includes/settings/tk-maya.yml
env/includes/settings/tk-shell.yml

(reviewsubmission added to maya only in task/asset context)

Added reviewsubmission to tk-shell. Removed from general tk-maya.

---

core/templates.yml
env/includes/settings/apps/tk-multi-reviewsubmission.yml

Not making it a hook as it is supposed to be executed through a subprocess running "nuke -t".

#563: Add reviewsubmission nuke script as an app setting.

---

env/includes/settings/apps/tk-multi-loader2.yml
env/includes/settings/apps/tk-multi-shotgunpanel.yml
hooks/tk-multi-loader2/tk-nuke_actions.py
hooks/tk-multi-shotgunpanel/tk-maya_actions.py
hooks/tk-multi-shotgunpanel/tk-nuke_actions.py

added support for UDIM Image PublishedFileType in loader, added support for FBX and Deep EXRs in nuke loader.

#934: Using mel to create file texture in maya

---

hooks/tk-multi-workfiles2/scene_operation_tk-maya.py

tk-multi-workfiles - get maya defaults from prefs named sgtk_*

---

env/includes/engine_locations.yml
env/includes/settings/apps/tk-multi-loader2.yml
env/includes/settings/apps/tk-multi-shotgunpanel.yml
hooks/tk-multi-loader2/tk-nuke_actions.py
hooks/tk-multi-publish2/maya/publish_files_integ.py
hooks/tk-multi-publish2/nuke/publish_files.py
hooks/tk-multi-shotgunpanel/tk-maya_actions.py
hooks/tk-multi-shotgunpanel/tk-nuke_actions.py
hooks/tk-multi-workfiles2/scene_operation_tk-maya.py

Original pull requests: #59, #60, #61, #62.
* tk-multi-publish2: nuke validations - better message about invalid paths
* tk-multi-workfiles2: make maya default render attributes configurable
* tk-multi-loader2: support for UDIM textures, fbx geo and deep exrs

Merge #918, #934, #935 into 3.x

---

env/includes/settings/tk-nukestudio.yml
hooks/tk-multi-publish2/ingest/collector.py

collector.py : private method was changed to protected to access function.

collector.py : private method was changed to protected to access function.

---

hooks/tk-multi-publish2/maya/publish_session_model.py

#1262: tk-multi-publish2 - update publish_session_model for modelpublish-8.7.0+

---

hooks/tk-multi-publish2/maya/publish_session_model.py

Also, retain only node <assetname> in published file (delete rest), but keep entire contents in work file while versioning up.

#1279: run modelling validations on node <assetname> only

---

env/includes/settings/apps/tk-multi-loader2.yml
hooks/tk-multi-loader2/tk-nuke_actions.py
hooks/tk-multi-publish2/ingest/color_process_files.py
hooks/tk-multi-publish2/ingest/ingest_files.py

Also, updated variable order in method signature to match shotgun's.

#1345: Add knobs that contain metadata from SG onto read nodes

---

hooks/tk-multi-publish2/maya/publish_integ.py
hooks/tk-multi-publish2/nuke/publish.py

error only if frame range is less than shotgun frame range

#1516: integ publish - allow excess playblast over shotgun 

---

env/includes/settings/apps/tk-multi-loader2.yml
hooks/tk-multi-loader2/tk-mari_actions.py

Requires https://github.com/mbrainerd/tk-mari/pull/4 to be approved before merging.

#1500: tk-multi-loader2, mari - add swap_geometry action

---

env/includes/app_locations.yml
env/includes/settings/apps/tk-multi-timelogger.yml
env/includes/settings/tk-houdini.yml
env/includes/settings/tk-mari.yml
env/includes/settings/tk-maya.yml
env/includes/settings/tk-nuke.yml
env/includes/settings/tk-nukestudio.yml

Changes in combination with [tk-multi-timelogger](http://dd-git.d2.com/india/tk-multi-timelogger/tree/feature-1591)

Feature 1591

---

hooks/tk-multi-workfiles2/scene_operation_tk-maya.py

sgtk_render_settings:
defaultResolution:
other:
deviceAspectRatio:
value: 1.555
vray:
other: # just set value
imageFormatStr: 
value: exr (multichannel)
type: string
arnold:
enum_attr:
exrCompression: dwaa
Added deviceAspectRatio and exrCompression in maya_preferences.yaml

#1679 update deviceAspectRatio and exr_compression on file save or New_file

---

env/includes/frameworks.yml
hooks/tk-framework-qtwidgets/external_screenshot.py

Depends on https://github.com/mbrainerd/tk-framework-qtwidgets/pull/1

#2236: tk-framework-qtwidgets - run screen grab subprocess in clean env

---

hooks/tk-multi-publish2/maya/publish_files_integ.py
hooks/tk-multi-publish2/maya/publish_session_integ.py

Also, split publish session, file into separate files. 
Some comment, function naming clean up.

#2269: integ publish - import all references in published file

---

hooks/tk-multi-publish2/maya/publish_session_rig.py

Replicated model publish validations for rig publish sessions.

Added rigging publish validations

---

core/schema/project/SHARED/PROJECT/step.yml
core/schema/project/SHARED/PROJECT/step/asset_type.yml
core/schema/project/SHARED/PROJECT/step/asset_type/asset.yml
core/templates/nukestudio.yml

Got minor fix for task-2212 pull request from mike (remove department key).
Fixed in task-2212_beta branch.
Added PROJECT scheme in SHARED folder

#2212: added PROJECT schema in SHARED folder and removed department key

---

hooks/tk-multi-publish2/3de/collector.py
hooks/tk-multi-publish2/silhouette/collector.py

Since we are receiving plates with 07 padding, defined a new key "ingestSEQ" for BNW show.
ingestSEQ:
type: sequence
format_spec: '07'
alias: SEQ
Added key existence check before removing it from fields.

#3141: modified code to check key existence before removing

---

hooks/tk-multi-publish2/maya/collector_lod_geometry.py
hooks/tk-multi-publish2/maya/publish_lod_geometry.py

Depends on the fix in https://github.com/mbrainerd/tk-multi-publish2/pull/69 to work correctly.

#3595: collect and publish lod alembic in modelling role during publish

---

core/templates/maya.yml
hooks/tk-multi-workfiles2/scene_operation_tk-maya.py

Turning off the locks for only those attributes which are being overwritten by atomic

Feature 2237

---

core/hooks/pick_environment.py

This modification will help to enable project based workflow

#2813: updated pickEnvironment to return project if entity type is Project

---

core/templates/houdini.yml

Added flipbook templates for houdini

Feature 3743

---

hooks/tk-multi-publish2/ingest/collector.py

Better handling of case where number of notes, snapshots and versions is unequal.

#3736: rely solely on notes block for notes ingestion

---

hooks/tk-multi-publish2/nuke/publish.py
hooks/tk-multi-publish2/nuke/publish_comp.py

Log warning or error based on log_method. Also removed the redundant method from publish_comp

Modified _framerange_to_be_published to accept log method 

---

hooks/tk-multi-publish2/maya/collector_lod_geometry.py
hooks/tk-multi-publish2/maya/publish_lod_geometry.py

to prevent abcExport from erroring out

#4589: collector, publish_lod_geometry - use full name of node

---

core/templates.yml
env/includes/settings/apps/tk-multi-reviewsubmission.yml
hooks/tk-multi-reviewsubmission/preprocess_nuke.py

tk-multi-reviewsubmission/v0.x.x/info.yaml
```
entity_burnin_sg_fields:
type: list
values: {type: str}
default_value: []
description: SG fields on entity to be added as burnins on slate
task_burnin_sg_fields:
type: list
values: {type: str}
default_value: []
description: SG fields on task to be added as burnins on slate
```
Will create pull request for above once I have git permissions

Feature 4558

---

env/includes/settings/apps/tk-multi-timelogger.yml
env/includes/settings/apps/tk-multi-workfiles2.yml

Misc Tasks tab for all time log related tasks

Feature 5778
